const cardData = [
    {
        name: 'Rick Sanchez',
        image: '/images/img1.webp',
        status: 'alive',
        species: 'Human',
        gender: 'Male',
      },
      {
        name: 'Morty Smith',
        image: '../images/img2.webp',
        status: 'alive',
        species: 'Human',
        gender: 'Male',
      },
      {
        name: 'Summer Smith',
        image: '../images/img3.webp',
        status: 'alive',
        species: 'Human',
        gender: 'Female',
      },
      {
          name: 'Abradolf Lincler',
          image: '../images/img4.webp',
          status: 'unknown',
          species: 'Human',
          gender: 'Male',
        },
        {
          name: 'Adjudicator Rick',
          image: '../images/img5.webp',
          status: 'dead',
          species: 'Human',
          gender: 'Male',
        },
        {
          name: 'Agency Director',
          image: '../images/img6.webp',
          status: 'dead',
          species: 'Human',
          gender: 'Male',
        },
         {
          name: 'Alan Rails',
          image: '../images/img7.webp',
          status: 'dead',
          species: 'Human',
          gender: 'Male',
        },
        {
          name: 'Albert Einstein',
          image: '../images/img8.webp',
          status: 'dead',
          species: 'Human',
          gender: 'Male',
        },
        {
          name: 'Alexander',
          image: '../images/img9.webp',
          status: 'dead',
          species: 'Human',
          gender: 'Male',
        },
        {
          name: 'Alien Googah',
          image: '../images/img10.webp',
          status: 'unknown',
          species: 'Alien',
          gender: 'unknown',
        },
        {
          name: 'Alien Morty',
          image: '../images/img11.webp',
          status: 'unknown',
          species: 'Alien',
          gender: 'Male',
        },
        {
          name: 'Alien Rick',
          image: '../images/img12.webp',
          status: 'unknown',
          species: 'Alien',
          gender: 'Male',
        },
        {
          name: 'Amish Cyborg',
          image: '../images/img13.webp',
          status: 'died',
          species: 'Alien',
          gender: 'Male',
        },
        {
          name: 'Annie',
          image: '../images/img14.webp',
          status: 'alive',
          species: 'Human',
          gender: 'Female',
        },
        {
          name: 'Antenna Morty',
          image: '../images/img15.webp',
          status: 'alive',
          species: 'Human',
          gender: 'Female',
        },
        {
          name: 'Antenna Rick',
          image: '../images/img16.webp',
          status: 'unknown',
          species: 'Human',
          gender: 'Male',
        },
        {
          name: 'Ants in my Eyes Johnson',
          image: '../images/img17.webp',
          status: 'unknown',
          species: 'Human',
          gender: 'Female',
        },
        {
          name: 'Aqua Morty',
          image: '/images/img18.webp',
          status: 'unknown',
          species: 'Humanoid',
          gender: 'Male',
        },
        {
          name: 'Aqua Rick',
          image: '../images/img19.webp',
          status: 'unknown',
          species: 'Humanoid',
          gender: 'Male',
        },
        {
          name: 'Arcade Alien',
          image: '../images/img20.webp',
          status: 'unknown',
          species: 'Alien',
          gender: 'Male',
        },
        {
            name: 'Armagheadon',
            image: '../images/img21.webp',
            status: 'alive',
            species: 'Alien',
            gender: 'Male',
          },
          {
            name: 'Armothy',
            image: '../images/img22.webp',
            status: 'dead',
            species: 'unknown',
            gender: 'Male',
          },
          {
            name: 'Arthricia',
            image: '../images/img23.webp',
            status: 'alive',
            species: 'Alien',
            gender: 'female',
          },
           {
            name: 'Artist Morty',
            image: '../images/img24.webp',
            status: 'alive',
            species: 'Human',
            gender: 'Male',
          },
          {
            name: 'Attila Starwar',
            image: '../images/img25.webp',
            status: 'alive',
            species: 'Human',
            gender: 'Male',
          },
          {
            name: 'Baby Legs',
            image: '../images/img26.webp',
            status: 'alive',
            species: 'Human',
            gender: 'Male',
          },
          {
            name: 'Baby Poopybutthole',
            image: '../images/img27.webp',
            status: 'alive',
            species: 'Poopybutthole',
            gender: 'Male',
          },
          {
            name: 'Baby Wizard',
            image: '../images/img28.webp',
            status: 'dead',
            species: 'Alien',
            gender: 'Male',
          },
          {
            name: 'Bearded Lady',
            image: '../images/img29.webp',
            status: 'dead',
            species: 'Alien',
            gender: 'Female',
          },
          {
            name: 'Beebo',
            image: '../images/img30.webp',
            status: 'died',
            species: 'Alien',
            gender: 'Male',
          },
          {
            name: 'Benjamin',
            image: '../images/img31.webp',
            status: 'alive',
            species: 'Poopybutthole',
            gender: 'Male',
          },
          {
            name: 'Bepisian',
            image: '../images/img32.webp',
            status: 'alive',
            species: 'Alien',
            gender: 'unknown',
          },
          {
            name: 'Beta-Seven',
            image: '../images/img33.webp',
            status: 'alive',
            species: 'Alien',
            gender: 'unknown',
          },
          {
            name: 'Beth Sanchez',
            image: '../images/img34.webp',
            status: 'alive',
            species: 'Human',
            gender: 'Female',
          },
          {
            name: 'Beth Smith',
            image: '../images/img35.webp',
            status: 'alive',
            species: 'Human',
            gender: 'Female',
          },{
            name: 'Beth Smith',
            image: '../images/img36.webp',
            status: 'alive',
            species: 'Human',
            gender: 'Female',
          },{
            name: "Beth's Mytholog",
            image: '../images/img37.webp',
            status: 'alive',
            species: 'Human',
            gender: 'Female',
          },{
            name: 'Big Boobed Waitress',
            image: '../images/img38.webp',
            status: 'alive',
            species: 'Mythological Creature',
            gender: 'Female',
          },{
            name: 'Big Head Morty',
            image: '../images/img39.webp',
            status: 'unknown',
            species: 'Human',
            gender: 'Male',
          },{
            name: 'Big Morty',
            image: '../images/img40.webp',
            status: 'dead',
            species: 'Human',
            gender: 'Male',
          },{
            name: 'Body Guard Morty',
            image: '../images/img41.webp',
            status: 'dead',
            species: 'Human',
            gender: 'Male',
          },{
            name: 'Bill',
            image: '../images/img42.webp',
            status: 'alive',
            species: 'Human',
            gender: 'Male',
          },{
            name: 'Bill',
            image: '../images/img43.webp',
            status: 'unknown',
            species: 'Animal',
            gender: 'Male',
          },{
            name: 'Birdperson',
            image: '../images/img34.webp',
            status: 'alive',
            species: 'Alien',
            gender: 'Male',
          },{
            name: 'Black Rick',
            image: '../images/img44.webp',
            status: 'alive',
            species: 'Human',
            gender: 'Male',
          },{
            name: 'Blamph',
            image: '../images/img45.webp',
            status: 'alive',
            species: 'Alien',
            gender: 'unknown',
          },{
            name: 'Blim Blam',
            image: '../images/img46.webp',
            status: 'alive',
            species: 'Alien',
            gender: 'Male',
          },{
            name: 'Blue Diplomat',
            image: '../images/img47.webp',
            status: 'alive',
            species: 'Alien',
            gender: 'Male',
          },{
            name: 'Blue Footprint Guy',
            image: '../images/img48.webp',
            status: 'dead',
            species: 'Human',
            gender: 'Male',
          },{
            name: 'Blue Shirt Morty',
            image: '../images/img49.webp',
            status: 'unknown',
            species: 'Human',
            gender: 'Male',
          },
          {
            name: 'Bobby Moynihan',
            image: '../images/img50.webp',
            status: 'alive',
            species: 'Human',
            gender: 'Male',
          },
          {
            name: 'Bootleg Portal Chemist Rick',
            image: '../images/img51.webp',
            status: 'dead',
            species: 'Human',
            gender: 'unknown',
          }  ,
          {
            name: 'Calypso',
            image: '../images/img52.webp',
            status: 'dead',
            species: 'Human',
            gender: 'female',
          }  ,
          {
            name: 'Campaign Manager Morty',
            image: '../images/img53.webp',
            status: 'dead',
            species: 'Human',
            gender: 'Male',
          } , 
          {
            name: 'Canklanker Thom',
            image: '../images/img54.webp',
            status: 'dead',
            species: 'Alien',
            gender: 'Male',
          }  ,
          {
            name: 'Centaur',
            image: '../images/img55.webp',
            status: 'alive',
            species: 'Mythological Creature',
            gender: 'Male',
          }  
          ,
          {
            name: 'Chris',
            image: '../images/img56.webp',
            status: 'dead',
            species: 'Alien',
            gender: 'unknown',
          }   ,
          {
            name: 'Chris',
            image: '../images/img57.webp',
            status: 'alive',
            species: 'Humanoid',
            gender: 'Male',
          }   ,
          {
            name: 'Coach Feratu',
            image: '../images/img58.webp',
            status: 'dead',
            species: 'Mythological Creature',
            gender: 'Male',
          }   ,
          {
            name: 'Collector',
            image: '../images/img59.webp',
            status: 'alive',
            species: 'Alien',
            gender: 'Male',
          }   ,
          {
            name: 'Colossus',
            image: '../images/img60.webp',
            status: 'dead',
            species: 'Human',
            gender: 'Male',
          }   ,
          {
            name: 'Commander Rick',
            image: '../images/img61.webp',
            status: 'dead',
            species: 'Human',
            gender: 'Male',
          }   ,
          {
            name: 'Concerto',
            image: '../images/img62.webp',
            status: 'dead',
            species: 'Humanoid',
            gender: 'Male',
          }   ,
          {
            name: 'Conroy',
            image: '../images/img63.webp',
            status: 'dead',
            species: 'Robot',
            gender: 'unknown',
          }   ,
          {
            name: 'Cool Rick',
            image: '../images/img64.webp',
            status: 'alive',
            species: 'Human',
            gender: 'Male',
          }   ,
          {
            name: 'Cop Morty',
            image: '../images/img65.webp',
            status: 'dead',
            species: 'Human',
            gender: 'Male',
          }   ,
          {
            name: 'Cop Rick',
            image: '../images/img66.webp',
            status: 'alive',
            species: 'Human',
            gender: 'Male',
          }   ,
          {
            name: 'Courier Flap',
            image: '../images/img67.webp',
            status: 'alive',
            species: 'Alien',
            gender: 'unknown',
          }   ,
          {
            name: 'Cousin Nicky',
            image: '../images/img68.webp',
            status: 'dead',
            species: 'Alien',
            gender: 'Male',
          }   ,
          {
            name: 'Cowboy Morty',
            image: '../images/img70.webp',
            status: 'alive',
            species: 'Human',
            gender: 'Male',
          }   ,
          {
            name: 'Cowboy Rick',
            image: '../images/img71.webp',
            status: 'alive',
            species: 'Human',
            gender: 'Male',
          }   ,
          {
            name: 'Crab Spider',
            image: '../images/img72.webp',
            status: 'alive',
            species: 'Alien',
            gender: 'unknown',
          }  
          ,
          {
            name: 'Creepy Little Girl',
            image: '../images/img73.webp',
            status: 'alive',
            species: 'Human',
            gender: 'Female',
          }  
  ];
  
  export default cardData;
  